In [1]:
#Olá! Meu nome é Ana Maria de Oliveira Yamakami, espero que gostem do meu código!

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
import numpy as np
import pandas as pd
#importando bibliotecas


pokemon = pd.read_csv('/content/drive/My Drive/Visagio/aula_1_pokemon.csv')
#pokemon

#Exercício 3.1
print("Resolução Exercício 3.1")

# lista de pesos de castanhas
c_peso = [0.946, 0.918, 0.906, 0.904, 0.858, 0.774, 0.652, 0.516, 0.478, 0.404, 0.396, 0.364, 0.342, 0.304, 
            0.262, 0.208, 0.134, 0.974, 0.792, 0.792, 0.628, 0.552, 0.506, 0.478, 0.462, 0.436, 0.408, 0.378, 
            0.3, 0.298, 0.268, 0.252, 0.16, 0.114, 0.092, 0.936, 0.894, 0.744, 0.706, 0.694, 0.69, 0.652, 0.518, 
            0.508, 0.502, 0.5, 0.47, 0.44, 0.39, 0.384]

# Importe o numpy como np
import numpy as np

# Crie um numpy array a partir de c_peso: np_c_peso
np_c_peso = np.array(c_peso)

# Imprima o tipo de np_c_peso
print("Tipo de np_c_peso: " + str(type(np_c_peso)))

c_kg_preco = 45

# Crie um array a partir de c_peso com a quantia gasta em cada compra: np_c_despesa
np_c_kg_preco = np.array(c_kg_preco)
np_c_despesa = np_c_kg_preco*np.array(c_peso)
print("Array np_c_despesa: " + str(np_c_despesa))
print("Tipo de np_c_despesa: "+ str(type(np_c_despesa)))

# Imprima o peso no indíce 20
print("Peso no indíce 20: "+ str(np_c_peso[21]))

Resolução Exercício 3.1
Tipo de np_c_peso: <class 'numpy.ndarray'>
Array np_c_despesa: [42.57 41.31 40.77 40.68 38.61 34.83 29.34 23.22 21.51 18.18 17.82 16.38
 15.39 13.68 11.79  9.36  6.03 43.83 35.64 35.64 28.26 24.84 22.77 21.51
 20.79 19.62 18.36 17.01 13.5  13.41 12.06 11.34  7.2   5.13  4.14 42.12
 40.23 33.48 31.77 31.23 31.05 29.34 23.31 22.86 22.59 22.5  21.15 19.8
 17.55 17.28]
Tipo de np_c_despesa: <class 'numpy.ndarray'>
Peso no indíce 20: 0.552

In [4]:
#Exercício 3.2
print ("Exercício 3.2")

castanha = [[2, 0.946, 66.1], 
          [2, 0.918, 32.96], 
          [2, 0.906, 58.76],
          [2, 0.904, 29.14], 
          [2, 0.858, 59.96],
          [2, 0.774, 27.77],
          [2, 0.652, 42.3],
          [2, 0.516, 18.51], 
          [2, 0.478, 17.15],
          [2, 0.404, 28.22], 
          [2, 0.396, 7.88], 
          [2, 0.364, 7.24],
          [2, 0.342, 22.18], 
          [2, 0.304, 10.91], 
          [2, 0.262, 9.41], 
          [2, 0.208, 4.13],
          [2, 0.134, 9.36],
          [4, 0.974, 34.95],
          [4, 0.792, 51.38],
          [4, 0.792, 51.38], 
          [4, 0.628, 12.48], 
          [4, 0.552, 19.81], 
          [4, 0.506, 25], 
          [4, 0.478, 31], 
          [4, 0.462, 32.24],
          [4, 0.436, 28.28],
          [4, 0.408, 14.64],
          [4, 0.378, 13.56],
          [4, 0.3, 19.46],
          [4, 0.298, 10.69],
          [4, 0.268, 9.62],
          [4, 0.252, 16.34],
          [4, 0.16, 3.18],
          [4, 0.114, 4.09],
          [4, 0.092, 5.97],
          [5, 0.936, 65.33],
          [5, 0.894, 32.07],
          [5, 0.744, 48.28], 
          [5, 0.706, 25.34],
          [5, 0.694, 24.91], 
          [5, 0.69, 13.72], 
          [5, 0.652, 42.32], 
          [5, 0.518, 33.6], 
          [5, 0.508, 18.23],
          [5, 0.502, 35.09],
          [5, 0.5, 27.45], 
          [5, 0.47, 9.35], 
          [5, 0.44, 28.54],
          [5, 0.39, 7.76], 
          [5, 0.384, 21.08]]

# Crie um numpy array 2d a partir de castanha: np_castanha
np_castanha = np.array(castanha)

# Imprima o tipo de np_castanha
print("Tipo de np_castanha: "+ str(type(np_castanha)))

# Imprima a forma de np_castanha
print("Forma de np_castanha: "+ str(np_castanha.shape))

# Selecione toda a segunda coluna de np_castanha: np_c_peso
print("Segunda coluna de np_castanha selecionada: ")
np_castanha[:,1]

# Imprima o preço da 14 venda
print("Preço da 14ª venda: "+ str(np_castanha[13,2]))

# Imprima todas as vendas feitas após o dia 2
print("Vendas feitas após o dia 2: "+ str(np_castanha[np_castanha[:,0]>2]))

Exercício 3.2
Tipo de np_castanha: <class 'numpy.ndarray'>
Forma de np_castanha: (50, 3)
Segunda coluna de np_castanha selecionada:
Preço da 14ª venda: 10.91
Vendas feitas após o dia 2: [[ 4.     0.974 34.95 ]
 [ 4.     0.792 51.38 ]
 [ 4.     0.792 51.38 ]
 [ 4.     0.628 12.48 ]
 [ 4.     0.552 19.81 ]
 [ 4.     0.506 25.   ]
 [ 4.     0.478 31.   ]
 [ 4.     0.462 32.24 ]
 [ 4.     0.436 28.28 ]
 [ 4.     0.408 14.64 ]
 [ 4.     0.378 13.56 ]
 [ 4.     0.3   19.46 ]
 [ 4.     0.298 10.69 ]
 [ 4.     0.268  9.62 ]
 [ 4.     0.252 16.34 ]
 [ 4.     0.16   3.18 ]
 [ 4.     0.114  4.09 ]
 [ 4.     0.092  5.97 ]
 [ 5.     0.936 65.33 ]
 [ 5.     0.894 32.07 ]
 [ 5.     0.744 48.28 ]
 [ 5.     0.706 25.34 ]
 [ 5.     0.694 24.91 ]
 [ 5.     0.69  13.72 ]
 [ 5.     0.652 42.32 ]
 [ 5.     0.518 33.6  ]
 [ 5.     0.508 18.23 ]
 [ 5.     0.502 35.09 ]
 [ 5.     0.5   27.45 ]
 [ 5.     0.47   9.35 ]
 [ 5.     0.44  28.54 ]
 [ 5.     0.39   7.76 ]
 [ 5.     0.384 21.08 ]]

In [5]:
#Exercício 3.3
print("Exercício 3.3")

# leia o arquivo (tente abrir num editor de texto antes para verificar o separador)
fut_players = pd.read_csv('/content/drive/My Drive/Visagio/aula_1_fut_players.csv')
#fut_players

# mostre as primeiras 10 linhas de dados
fut_players.head(10)

Exercício 3.3

   player_id  ... base_id
0          1  ...  237067
1          2  ...  190042
2          3  ...   37576
3          4  ...  237068
4          5  ...  237074
5          6  ...  238439
6          7  ...  237064
7          8  ...  238380
8          9  ...   28130
9         10  ...  192181

[10 rows x 82 columns]

In [6]:
# mostre as últimas 10 linhas de dados
fut_players.tail(10)

       player_id     player_name  ... specialities base_id
18821      19298           Angol  ...          NaN  210244
18822      19299  Mendoza Hansen  ...          NaN  215656
18823      19300         Piossek  ...          NaN  197148
18824      19301         Bingham  ...          NaN  209462
18825      19302          Gibson  ...          NaN  240813
18826      19303           Shala  ...          NaN  205423
18827      19304           Boyer  ...          NaN  208832
18828      19305           Arias  ...          NaN  226122
18829      19306     Moses Ekpai  ...          NaN  244790
18830      19307          Diallo  ...          NaN  233902

[10 rows x 82 columns]

In [7]:
# use o método .info() no DataFrame
fut_players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18831 entries, 0 to 18830
Data columns (total 82 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   player_id             18831 non-null  int64
 1   player_name           18831 non-null  object
 2   player_extended_name  18831 non-null  object
 3   quality               18831 non-null  object
 4   revision              18826 non-null  object
 5   origin                2478 non-null   object
 6   overall               18831 non-null  int64
 7   club                  18831 non-null  object
 8   league                18831 non-null  object
 9   nationality           18831 non-null  object
 10  position              18831 non-null  object
 11  age                   18831 non-null  int64
 12  date_of_birth         18831 non-null  object
 13  height                18831 non-null  int64
 14  weight                18831 non-null  int64
 15  intl_rep              18831 non-null  int64
 16  added_date            18831 non-null  object
 17  pace                  16882 non-null  float64
 18  pace_acceleration     18831 non-null  int64
 19  pace_sprint_speed     18831 non-null  int64
 20  dribbling             16882 non-null  float64
 21  drib_agility          18831 non-null  int64
 22  drib_balance          18831 non-null  int64
 23  drib_reactions        18831 non-null  int64
 24  drib_ball_control     18831 non-null  int64
 25  drib_dribbling        18831 non-null  int64
 26  drib_composure        18831 non-null  int64
 27  shooting              16882 non-null  float64
 28  shoot_positioning     18831 non-null  int64
 29  shoot_finishing       18831 non-null  int64
 30  shoot_shot_power      18831 non-null  int64
 31  shoot_long_shots      18831 non-null  int64
 32  shoot_volleys         18831 non-null  int64
 33  shoot_penalties       18831 non-null  int64
 34  passing               16882 non-null  float64
 35  pass_vision           18831 non-null  int64
 36  pass_crossing         18831 non-null  int64
 37  pass_free_kick        18831 non-null  int64
 38  pass_short            18831 non-null  int64
 39  pass_long             18831 non-null  int64
 40  pass_curve            18831 non-null  int64
 41  defending             16882 non-null  float64
 42  def_interceptions     18831 non-null  int64
 43  def_heading           18831 non-null  int64
 44  def_marking           18831 non-null  int64
 45  def_stand_tackle      18831 non-null  int64
 46  def_slid_tackle       18831 non-null  int64
 47  physicality           16882 non-null  float64
 48  phys_jumping          18831 non-null  int64
 49  phys_stamina          18831 non-null  int64
 50  phys_strength         18831 non-null  int64
 51  phys_aggression       18831 non-null  int64
 52  gk_diving             1949 non-null   float64
 53  gk_reflexes           1949 non-null   float64
 54  gk_handling           1949 non-null   float64
 55  gk_speed              1949 non-null   float64
 56  gk_kicking            1949 non-null   float64
 57  gk_positoning         1949 non-null   float64
 58  pref_foot             18831 non-null  object
 59  att_workrate          18831 non-null  object
 60  def_workrate          18831 non-null  object
 61  weak_foot             18831 non-null  int64
 62  skill_moves           18831 non-null  int64
 63  cb                    16882 non-null  float64
 64  rb                    16882 non-null  float64
 65  lb                    16882 non-null  float64
 66  rwb                   16882 non-null  float64
 67  lwb                   16882 non-null  float64
 68  cdm                   16882 non-null  float64
 69  cm                    16882 non-null  float64
 70  rm                    16882 non-null  float64
 71  lm                    16882 non-null  float64
 72  cam                   16882 non-null  float64
 73  cf                    16882 non-null  float64
 74  rf                    16882 non-null  float64
 75  lf                    16882 non-null  float64
 76  rw                    16882 non-null  float64
 77  lw                    16882 non-null  float64
 78  st                    16882 non-null  float64
 79  traits                7151 non-null   object
 80  specialities          2380 non-null   object
 81  base_id               18831 non-null  int64
dtypes: float64(28), int64(38), object(16)
memory usage: 11.8+ MB

In [8]:
# mostre o resumo estatístico das colunas numericas
fut_players.describe()

          player_id       overall  ...            st        base_id
count  18831.000000  18831.000000  ...  16882.000000   18831.000000
mean    9724.997663     68.200839  ...     60.297832  209831.137114
std     5592.051018      8.143145  ...     10.213289   31943.691550
min        1.000000     47.000000  ...     31.000000      16.000000
25%     4846.500000     63.000000  ...     53.000000  194928.500000
50%     9805.000000     67.000000  ...     60.000000  214860.000000
75%    14581.500000     73.000000  ...     67.000000  232590.500000
max    19307.000000     99.000000  ...     98.000000  245714.000000

[8 rows x 66 columns]

In [9]:
#Exercício 3.4
print("Exercício 3.4")

# mostre as 5 primeiras linhas das colunas player_name, position and nationality
fut_players[['player_name', 'position', 'nationality']].head()

Exercício 3.4

  player_name position nationality
0        Pelé      CAM      Brazil
1    Maradona      CAM   Argentina
2     Ronaldo       ST      Brazil
3        Pelé       CF      Brazil
4    Maradona      CAM   Argentina

In [10]:
#renomeie as colunas player_id, player_name and player_extended_name para id, name and extended_name, respectivamente
fut_players.rename(
    columns={'player_id' : 'id','player_name' : 'name', 'player_extended_name' : 'extended_name'},
    inplace=True
)

fut_players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18831 entries, 0 to 18830
Data columns (total 82 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 18831 non-null  int64
 1   name               18831 non-null  object
 2   extended_name      18831 non-null  object
 3   quality            18831 non-null  object
 4   revision           18826 non-null  object
 5   origin             2478 non-null   object
 6   overall            18831 non-null  int64
 7   club               18831 non-null  object
 8   league             18831 non-null  object
 9   nationality        18831 non-null  object
 10  position           18831 non-null  object
 11  age                18831 non-null  int64
 12  date_of_birth      18831 non-null  object
 13  height             18831 non-null  int64
 14  weight             18831 non-null  int64
 15  intl_rep           18831 non-null  int64
 16  added_date         18831 non-null  object
 17  pace               16882 non-null  float64
 18  pace_acceleration  18831 non-null  int64
 19  pace_sprint_speed  18831 non-null  int64
 20  dribbling          16882 non-null  float64
 21  drib_agility       18831 non-null  int64
 22  drib_balance       18831 non-null  int64
 23  drib_reactions     18831 non-null  int64
 24  drib_ball_control  18831 non-null  int64
 25  drib_dribbling     18831 non-null  int64
 26  drib_composure     18831 non-null  int64
 27  shooting           16882 non-null  float64
 28  shoot_positioning  18831 non-null  int64
 29  shoot_finishing    18831 non-null  int64
 30  shoot_shot_power   18831 non-null  int64
 31  shoot_long_shots   18831 non-null  int64
 32  shoot_volleys      18831 non-null  int64
 33  shoot_penalties    18831 non-null  int64
 34  passing            16882 non-null  float64
 35  pass_vision        18831 non-null  int64
 36  pass_crossing      18831 non-null  int64
 37  pass_free_kick     18831 non-null  int64
 38  pass_short         18831 non-null  int64
 39  pass_long          18831 non-null  int64
 40  pass_curve         18831 non-null  int64
 41  defending          16882 non-null  float64
 42  def_interceptions  18831 non-null  int64
 43  def_heading        18831 non-null  int64
 44  def_marking        18831 non-null  int64
 45  def_stand_tackle   18831 non-null  int64
 46  def_slid_tackle    18831 non-null  int64
 47  physicality        16882 non-null  float64
 48  phys_jumping       18831 non-null  int64
 49  phys_stamina       18831 non-null  int64
 50  phys_strength      18831 non-null  int64
 51  phys_aggression    18831 non-null  int64
 52  gk_diving          1949 non-null   float64
 53  gk_reflexes        1949 non-null   float64
 54  gk_handling        1949 non-null   float64
 55  gk_speed           1949 non-null   float64
 56  gk_kicking         1949 non-null   float64
 57  gk_positoning      1949 non-null   float64
 58  pref_foot          18831 non-null  object
 59  att_workrate       18831 non-null  object
 60  def_workrate       18831 non-null  object
 61  weak_foot          18831 non-null  int64
 62  skill_moves        18831 non-null  int64
 63  cb                 16882 non-null  float64
 64  rb                 16882 non-null  float64
 65  lb                 16882 non-null  float64
 66  rwb                16882 non-null  float64
 67  lwb                16882 non-null  float64
 68  cdm                16882 non-null  float64
 69  cm                 16882 non-null  float64
 70  rm                 16882 non-null  float64
 71  lm                 16882 non-null  float64
 72  cam                16882 non-null  float64
 73  cf                 16882 non-null  float64
 74  rf                 16882 non-null  float64
 75  lf                 16882 non-null  float64
 76  rw                 16882 non-null  float64
 77  lw                 16882 non-null  float64
 78  st                 16882 non-null  float64
 79  traits             7151 non-null   object
 80  specialities       2380 non-null   object
 81  base_id            18831 non-null  int64
dtypes: float64(28), int64(38), object(16)
memory usage: 11.8+ MB

In [ ]:
#imprima a coluna extended_name do 4534º jogador usando loc e iloc
print("Coluna extended_name do 4534º jogador usando loc: "+ str(fut_players.loc[4534].extended_name))

print("Coluna extended_name do 4534º jogador usando iloc: "+ str(fut_players.loc[4534].extended_name))

In [33]:
#nosso DataFrame tem muitas colunas
#crie outro DataFrame (fut_players_2) apenas com as colunas na lista abaixo
selected_columns = ['id', 'name', 'overall', 'nationality', 'position', 'pref_foot', 'base_id']

fut_players_2 = pd.DataFrame(fut_players[selected_columns])

fut_players_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18831 entries, 0 to 18830
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           18831 non-null  int64
 1   name         18831 non-null  object
 2   overall      18831 non-null  int64
 3   nationality  18831 non-null  object
 4   position     18831 non-null  object
 5   pref_foot    18831 non-null  object
 6   base_id      18831 non-null  int64
dtypes: int64(3), object(4)
memory usage: 1.0+ MB

In [35]:
#queremos ver os melhores jogadores nascidos no Brasil (Brazil), isto é, aqueles com médio (overall) acima de 90
#mostre os 15 primeiros

aux_1 = fut_players_2[(fut_players_2.nationality == 'Brazil')&(fut_players_2.overall > 90)]
aux_1.head(15)

          id        name  overall nationality position pref_foot  base_id
0          1        Pelé       98      Brazil      CAM     Right   237067
2          3     Ronaldo       96      Brazil       ST     Right    37576
3          4        Pelé       95      Brazil       CF     Right   237068
6          7     Ronaldo       94      Brazil       ST     Right   237064
8          9  Ronaldinho       94      Brazil       LW     Right    28130
37        38  Ronaldinho       91      Brazil      CAM     Right   238395
48        49        Pelé       91      Brazil       CF     Right   190043
51        52      Carlos       91      Brazil       LB      Left   238430
826      846   Neymar Jr       92      Brazil       LW     Right   190871
12632  13091     Rivaldo       92      Brazil       LW      Left     4231
12637  13096    Sócrates       91      Brazil      CAM     Right   190046
16491  16951   Neymar Jr       93      Brazil       LW     Right   190871
16551  17014   Neymar Jr       93      Brazil       LF     Right   190871
16923  17388   Neymar Jr       94      Brazil      CAM     Right   190871
17139  17604     Marcelo       94      Brazil       LB      Left   176676

In [36]:
#vários jogadores bons!
#agora mostre os jogadores brasileiros que sejam canhotos (pref_foot é Left) ou que sejam goleiros (position é GK)
aux_2 = fut_players_2[(fut_players_2.nationality == 'Brazil')&((fut_players_2.pref_foot == 'Left')|(fut_players_2.position == 'GK'))]
aux_2.head(20)

      id           name  overall nationality position pref_foot  base_id
51    52         Carlos       91      Brazil       LB      Left   238430
90    91         Carlos       88      Brazil       LB      Left     1040
121  122         Carlos       86      Brazil       LB      Left   237071
148  149    Alex Sandro       87      Brazil       LB      Left   191043
150  151  Douglas Costa       87      Brazil       LM      Left   190483
153  154  Douglas Costa       86      Brazil       LM      Left   190483
154  155    Alex Sandro       86      Brazil       LB      Left   191043
246  250           Fred       83      Brazil       CM      Left   209297
257  261           Fred       82      Brazil       CM      Left   209297
292  298        Ederson       87      Brazil       GK      Left   210257
296  302        Ederson       86      Brazil       GK      Left   210257
356  362         Malcom       84      Brazil       RW      Left   222737
358  364         Malcom       83      Brazil       RW      Left   222737
359  365        Rafinha       83      Brazil      CAM      Left   201400
363  369        Rafinha       82      Brazil      CAM      Left   201400
458  465        Alisson       86      Brazil       GK     Right   212831
464  471        Alisson       85      Brazil       GK     Right   212831
588  599        Marcelo       89      Brazil       LB      Left   176676
592  603        Marcelo       88      Brazil       LB      Left   176676
682  699       Raphinha       79      Brazil       RM      Left   233419

In [37]:
#Exercício 3.5
print("Exercício 3.5")

#the_best é um DataDrame dos melhores jogadores em drible (dribbling) e chute (shooting)
the_best = fut_players[(fut_players.dribbling > 90) & (fut_players.shooting > 90)][['id', 'name', 'position', 'dribbling', 'shooting', 'overall']]

#nationalities é um DataDrame da nacionalidade dos jogadores
nationalities = fut_players[['id', 'name', 'nationality']]

#faça um merge dos dois DataDrames para obter a nacionalidade dos melhores jogadores (dica: chave é o id)
the_best_nationality = pd.merge(the_best,nationalities, how='inner', on=['id','name'] )
the_best_nationality.head()

Exercício 3.5

   id      name position  dribbling  shooting  overall nationality
0   1      Pelé      CAM       96.0      96.0       98      Brazil
1   2  Maradona      CAM       97.0      93.0       97   Argentina
2   3   Ronaldo       ST       95.0      95.0       96      Brazil
3   4      Pelé       CF       95.0      93.0       95      Brazil
4   5  Maradona      CAM       95.0      91.0       95   Argentina

In [45]:
#Exercício 3.6
print("Exercício 3.6")

#cria o DataDrame country_avg_overall, que tem o overall médio de cada país (nationality), usando groupby
country_avg_overall = fut_players.groupby('nationality').overall.mean()

#usamos o método idxmax() para encontrar o maior overall médio
print("Melhor overall médio: \n", country_avg_overall.loc[country_avg_overall.idxmax()])
print("Overall médio do Brasil: ", country_avg_overall.loc["Brazil"])

Exercício 3.6
Melhor overall médio:
 79.0
Overall médio do Brasil:  75.21915584415585

In [66]:
#Exercício 3.7
print("Exercício 3.7")

#Crie uma função que retorna a classificação para o jogador de acordo com as instruções abaixo,
# então aplique isso para o dataframe fut_players.

def get_classification(overall):
    """
    Recebe um overall de algum jogador e retorna a classificação conforme a seguir:
    Overall -> classification
    -50     -> "Amador"
    50-60   -> "Ruim"
    60-70   -> "Ok"
    70-80   -> "Bom"
    80-90   -> "Ótimo"
    90+     -> "Lenda"
    
    I: int overall
    O: string
    """
    if overall <= 50:
      return("Amador")

    elif overall <= 60 :
      return("Ruim")

    elif overall <=70:
      return("Ok")

    elif overall <=80:
      return("Bom")

    elif overall <=90:
      return("Ótimo")

    elif overall> 90:
      return("Lenda")

fut_players["classification"] = fut_players['overall'].apply(get_classification)
fut_players.head()

Exercício 3.7

   id      name  ... base_id classification
0   1      Pelé  ...  237067          Lenda
1   2  Maradona  ...  190042          Lenda
2   3   Ronaldo  ...   37576          Lenda
3   4      Pelé  ...  237068          Lenda
4   5  Maradona  ...  237074          Lenda

[5 rows x 83 columns]